name: Release
on:
  push:
    tags:
      - ntakt-*
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"
      - name: Verify nta.kt version
        run: |
          NTAKT_VERSION=$(./gradlew properties | grep 'version:' | sed 's/version: //')
          echo NTAKT_VERSION=$NTAKT_VERSION >> $GITHUB_ENV
          echo NTAKT_VERSION=$NTAKT_VERSION
          echo GITHUB_REF=${{ github.ref }}
          [ "${{ github.ref }}" = "refs/tags/ntakt-$NTAKT_VERSION" ]
      - name: Build nta.kt and execute unit tests
        run: |
          ./gradlew clean build test publishToMavenLocal
      - name: Get artifact name
        run: |
          BASENAME="ntakt-${{ env.NTAKT_VERSION }}"
          ARTIFACT_NAME="$BASENAME.jar"
          ARTIFACT_PATH="build/libs/$ARTIFACT_NAME"
          POM_NAME="$BASENAME.pom"
          POM_PATH=build/publications/maven/pom-default.xml
          MODULE_NAME="$BASENAME.module"
          MODULE_PATH=build/publications/maven/module.json
          echo ARTIFACT_NAME=${ARTIFACT_NAME} >> $GITHUB_ENV
          echo ARTIFACT_PATH=${ARTIFACT_PATH} >> $GITHUB_ENV
          echo POM_NAME=$POM_NAME >> $GITHUB_ENV
          echo POM_PATH=$POM_PATH >> $GITHUB_ENV
          echo MODULE_NAME=$MODULE_NAME >> $GITHUB_ENV
          echo MODULE_PATH=$MODULE_PATH >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Nta.kt ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ARTIFACT_PATH }}
          asset_name: ${{ env.ARTIFACT_NAME }}
          asset_content_type: application/java-archive
      - name: Upload module json
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.MODULE_PATH }}
          asset_name: ${{ env.MODULE_NAME }}
          asset_content_type: application/java-archive
      - name: Upload pom
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.POM_PATH }}
          asset_name: ${{ env.POM_NAME }}
          asset_content_type: application/java-archive
      - run: echo "🍏 This job's status is ${{ job.status }}."
